name: flutter_clean_architecture
description: flutter clean architecture
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  flutter_riverpod: ^2.1.1
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true